/**
 * Predefined KPIs for Restaurant Groups (3-15 branches)
 * Based on HORECA industry standards and Pulso system capabilities
 */

export interface KpiTemplate {
  id: string;
  name: string;
  description: string;
  formula: string;
  metricType: "PERCENTAGE" | "COUNT" | "AVERAGE" | "SUM" | "TIME" | "RATIO";
  category: "OPERATIONS" | "COMPLIANCE" | "LABOR" | "INVENTORY";
  target: number;
  warningThreshold: number;
  criticalThreshold: number;
  thresholdType: "MIN" | "MAX" | "TARGET" | "RANGE";
  frequency: "REALTIME" | "HOURLY" | "DAILY" | "WEEKLY" | "MONTHLY";
  unit: string;
  decimalPlaces: number;
  applicableRoles: string[];
  benchmark: {
    industry: number;
    excellent: number;
    good: number;
    needsImprovement: number;
  };
}

// ============================================================================
// OPERATIONS KPIs - Core restaurant operational metrics
// ============================================================================

export const operationsKPIs: KpiTemplate[] = [
  // Workflow Completion
  {
    id: "ops-workflow-completion-rate",
    name: "Tasa de Completitud de Tareas (Checklist)",
    description: "Porcentaje de tareas diarias (apertura/cierre/limpieza) completadas a tiempo en todas las sucursales. Ideal para medir la disciplina operativa.",
    formula: "(completed_workflows / total_workflows) * 100",
    metricType: "PERCENTAGE",
    category: "OPERATIONS",
    target: 95,
    warningThreshold: 85,
    criticalThreshold: 75,
    thresholdType: "MIN",
    frequency: "DAILY",
    unit: "%",
    decimalPlaces: 1,
    applicableRoles: ["SUPER_ADMIN", "ADMIN", "GERENTE", "SUPERVISOR"],
    benchmark: {
      industry: 85,
      excellent: 98,
      good: 95,
      needsImprovement: 80,
    },
  },
  {
    id: "ops-on-time-completion",
    name: "Tasa de Puntualidad en Tareas",
    description: "Porcentaje de workflows completados dentro del horario establecido. Mide la eficiencia operativa y cumplimiento de horarios.",
    formula: "(on_time_workflows / completed_workflows) * 100",
    metricType: "PERCENTAGE",
    category: "OPERATIONS",
    target: 90,
    warningThreshold: 80,
    criticalThreshold: 70,
    thresholdType: "MIN",
    frequency: "DAILY",
    unit: "%",
    decimalPlaces: 1,
    applicableRoles: ["SUPER_ADMIN", "ADMIN", "GERENTE", "SUPERVISOR"],
    benchmark: {
      industry: 85,
      excellent: 95,
      good: 90,
      needsImprovement: 75,
    },
  },
  {
    id: "ops-avg-workflow-duration",
    name: "Duración Promedio de Tareas",
    description: "Tiempo promedio que toma completar un workflow por sucursal. Permite identificar procesos lentos o ineficientes.",
    formula: "AVG(workflow_duration_minutes)",
    metricType: "TIME",
    category: "OPERATIONS",
    target: 25,
    warningThreshold: 40,
    criticalThreshold: 60,
    thresholdType: "MAX",
    frequency: "DAILY",
    unit: "min",
    decimalPlaces: 0,
    applicableRoles: ["SUPER_ADMIN", "ADMIN", "GERENTE", "SUPERVISOR"],
    benchmark: {
      industry: 30,
      excellent: 20,
      good: 25,
      needsImprovement: 45,
    },
  },
  
  // Opening/Closing Efficiency
  {
    id: "ops-opening-efficiency",
    name: "Eficiencia de Apertura",
    description: "Porcentaje de aperturas completadas antes de la hora de apertura al público. Crítico para operaciones matutinas.",
    formula: "(early_openings / total_openings) * 100",
    metricType: "PERCENTAGE",
    category: "OPERATIONS",
    target: 95,
    warningThreshold: 85,
    criticalThreshold: 70,
    thresholdType: "MIN",
    frequency: "DAILY",
    unit: "%",
    decimalPlaces: 1,
    applicableRoles: ["SUPER_ADMIN", "ADMIN", "GERENTE"],
    benchmark: {
      industry: 90,
      excellent: 98,
      good: 95,
      needsImprovement: 80,
    },
  },
  {
    id: "ops-closing-efficiency",
    name: "Eficiencia de Cierre",
    description: "Porcentaje de cierres completados dentro del tiempo establecido. Impacta en costos laborales nocturnos.",
    formula: "(on_time_closings / total_closings) * 100",
    metricType: "PERCENTAGE",
    category: "OPERATIONS",
    target: 90,
    warningThreshold: 80,
    criticalThreshold: 65,
    thresholdType: "MIN",
    frequency: "DAILY",
    unit: "%",
    decimalPlaces: 1,
    applicableRoles: ["SUPER_ADMIN", "ADMIN", "GERENTE"],
    benchmark: {
      industry: 85,
      excellent: 95,
      good: 90,
      needsImprovement: 75,
    },
  },

  // Quality Control
  {
    id: "ops-quality-inspection-score",
    name: "Puntuación de Inspección de Calidad",
    description: "Puntuación promedio de inspecciones de calidad realizadas. Incluye limpieza, presentación y estándares.",
    formula: "(quality_passed / quality_total) * 100",
    metricType: "PERCENTAGE",
    category: "OPERATIONS",
    target: 92,
    warningThreshold: 85,
    criticalThreshold: 75,
    thresholdType: "MIN",
    frequency: "DAILY",
    unit: "%",
    decimalPlaces: 1,
    applicableRoles: ["SUPER_ADMIN", "ADMIN", "GERENTE", "SUPERVISOR"],
    benchmark: {
      industry: 88,
      excellent: 95,
      good: 92,
      needsImprovement: 80,
    },
  },
  {
    id: "ops-temperature-compliance",
    name: "Cumplimiento de Temperaturas",
    description: "Porcentaje de registros de temperatura dentro de rangos seguros (NOM-251). Crítico para inocuidad alimentaria.",
    formula: "(temp_compliant_readings / total_temp_readings) * 100",
    metricType: "PERCENTAGE",
    category: "OPERATIONS",
    target: 98,
    warningThreshold: 95,
    criticalThreshold: 90,
    thresholdType: "MIN",
    frequency: "REALTIME",
    unit: "%",
    decimalPlaces: 1,
    applicableRoles: ["SUPER_ADMIN", "ADMIN", "GERENTE", "SUPERVISOR"],
    benchmark: {
      industry: 95,
      excellent: 99,
      good: 98,
      needsImprovement: 90,
    },
  },

  // Branch Comparison
  {
    id: "ops-branch-performance-index",
    name: "Índice de Rendimiento por Sucursal",
    description: "Índice compuesto que evalúa el rendimiento general de cada sucursal (0-100). Incluye workflows, calidad y cumplimiento.",
    formula: "(workflow_score * 0.4) + (quality_score * 0.3) + (compliance_score * 0.3)",
    metricType: "PERCENTAGE",
    category: "OPERATIONS",
    target: 85,
    warningThreshold: 75,
    criticalThreshold: 60,
    thresholdType: "MIN",
    frequency: "WEEKLY",
    unit: "pts",
    decimalPlaces: 0,
    applicableRoles: ["SUPER_ADMIN", "ADMIN", "GERENTE"],
    benchmark: {
      industry: 80,
      excellent: 90,
      good: 85,
      needsImprovement: 70,
    },
  },

  // Overdue Tasks
  {
    id: "ops-overdue-tasks-count",
    name: "Tareas Vencidas",
    description: "Número de tareas que no se completaron dentro del tiempo programado. Indicador de sobrecarga o problemas operativos.",
    formula: "overdue_workflows",
    metricType: "COUNT",
    category: "OPERATIONS",
    target: 0,
    warningThreshold: 5,
    criticalThreshold: 10,
    thresholdType: "MAX",
    frequency: "DAILY",
    unit: "tareas",
    decimalPlaces: 0,
    applicableRoles: ["SUPER_ADMIN", "ADMIN", "GERENTE", "SUPERVISOR"],
    benchmark: {
      industry: 3,
      excellent: 0,
      good: 2,
      needsImprovement: 8,
    },
  },
  {
    id: "ops-overdue-rate",
    name: "Tasa de Vencimiento de Tareas",
    description: "Porcentaje de tareas que se vencieron respecto al total. Tasa de vencimiento aceptable para restaurantes: <5%.",
    formula: "(overdue_workflows / total_workflows) * 100",
    metricType: "PERCENTAGE",
    category: "OPERATIONS",
    target: 3,
    warningThreshold: 8,
    criticalThreshold: 15,
    thresholdType: "MAX",
    frequency: "DAILY",
    unit: "%",
    decimalPlaces: 1,
    applicableRoles: ["SUPER_ADMIN", "ADMIN", "GERENTE"],
    benchmark: {
      industry: 10,
      excellent: 2,
      good: 5,
      needsImprovement: 15,
    },
  },
];

// ============================================================================
// COMPLIANCE KPIs - Regulatory compliance metrics
// ============================================================================

export const complianceKPIs: KpiTemplate[] = [
  // NOM-251 (Food Safety)
  {
    id: "comp-nom251-compliance",
    name: "Cumplimiento NOM-251 (Inocuidad)",
    description: "Porcentaje de cumplimiento de la Norma NOM-251 (cofepris) relacionada con higiene y manejo de alimentos. Requisito legal obligatorio.",
    formula: "(nom251_completed / nom251_total) * 100",
    metricType: "PERCENTAGE",
    category: "COMPLIANCE",
    target: 100,
    warningThreshold: 95,
    criticalThreshold: 90,
    thresholdType: "MIN",
    frequency: "DAILY",
    unit: "%",
    decimalPlaces: 1,
    applicableRoles: ["SUPER_ADMIN", "ADMIN", "GERENTE"],
    benchmark: {
      industry: 95,
      excellent: 100,
      good: 98,
      needsImprovement: 90,
    },
  },
  {
    id: "comp-nom251-critical-items",
    name: "Cumplimiento Items Críticos NOM-251",
    description: "Cumplimiento específico de items críticos de NOM-251 (control de temperatura, higiene personal, limpieza de superficies).",
    formula: "(critical_items_passed / critical_items_total) * 100",
    metricType: "PERCENTAGE",
    category: "COMPLIANCE",
    target: 100,
    warningThreshold: 98,
    criticalThreshold: 95,
    thresholdType: "MIN",
    frequency: "DAILY",
    unit: "%",
    decimalPlaces: 1,
    applicableRoles: ["SUPER_ADMIN", "ADMIN", "GERENTE"],
    benchmark: {
      industry: 97,
      excellent: 100,
      good: 99,
      needsImprovement: 95,
    },
  },

  // NOM-035 (Psychosocial Risk)
  {
    id: "comp-nom035-compliance",
    name: "Cumplimiento NOM-035 (Riesgo Psicosocial)",
    description: "Porcentaje de cumplimiento de la Norma NOM-035 para identificación y prevención de riesgos psicosociales en el trabajo.",
    formula: "(nom035_completed / nom035_total) * 100",
    metricType: "PERCENTAGE",
    category: "COMPLIANCE",
    target: 100,
    warningThreshold: 90,
    criticalThreshold: 85,
    thresholdType: "MIN",
    frequency: "MONTHLY",
    unit: "%",
    decimalPlaces: 1,
    applicableRoles: ["SUPER_ADMIN", "ADMIN", "GERENTE"],
    benchmark: {
      industry: 90,
      excellent: 100,
      good: 95,
      needsImprovement: 85,
    },
  },
  {
    id: "comp-break-compliance",
    name: "Cumplimiento de Pausas Activas",
    description: "Porcentaje de empleados que tomaron sus pausas activas conforme a NOM-035. Requerido por ley para turnos >4 horas.",
    formula: "(compliant_breaks / total_breaks_required) * 100",
    metricType: "PERCENTAGE",
    category: "COMPLIANCE",
    target: 100,
    warningThreshold: 90,
    criticalThreshold: 80,
    thresholdType: "MIN",
    frequency: "DAILY",
    unit: "%",
    decimalPlaces: 1,
    applicableRoles: ["SUPER_ADMIN", "ADMIN", "GERENTE"],
    benchmark: {
      industry: 85,
      excellent: 98,
      good: 95,
      needsImprovement: 75,
    },
  },

  // Labor Law Compliance
  {
    id: "comp-labor-doc-compliance",
    name: "Cumplimiento Documental Laboral",
    description: "Porcentaje de expedientes de empleados con documentación completa (RFC, NSS, INE, contrato). Requerido por LFT.",
    formula: "(complete_employee_files / total_employees) * 100",
    metricType: "PERCENTAGE",
    category: "COMPLIANCE",
    target: 100,
    warningThreshold: 95,
    criticalThreshold: 90,
    thresholdType: "MIN",
    frequency: "MONTHLY",
    unit: "%",
    decimalPlaces: 1,
    applicableRoles: ["SUPER_ADMIN", "ADMIN", "GERENTE"],
    benchmark: {
      industry: 92,
      excellent: 100,
      good: 98,
      needsImprovement: 90,
    },
  },
  {
    id: "comp-overtime-compliance",
    name: "Cumplimiento de Horas Extra",
    description: "Porcentaje de registros de horas extra conforme a la Ley Federal del Trabajo (máx. 3 horas diarias, 3 veces/semana).",
    formula: "(compliant_overtime / total_overtime) * 100",
    metricType: "PERCENTAGE",
    category: "COMPLIANCE",
    target: 100,
    warningThreshold: 95,
    criticalThreshold: 85,
    thresholdType: "MIN",
    frequency: "WEEKLY",
    unit: "%",
    decimalPlaces: 1,
    applicableRoles: ["SUPER_ADMIN", "ADMIN", "GERENTE"],
    benchmark: {
      industry: 90,
      excellent: 100,
      good: 98,
      needsImprovement: 85,
    },
  },

  // AI Verification
  {
    id: "comp-ai-verification-rate",
    name: "Tasa de Verificación con IA",
    description: "Porcentaje de evidencias fotográficas verificadas automáticamente por IA. Reduce costos de supervisión manual.",
    formula: "(ai_verified_photos / total_photos) * 100",
    metricType: "PERCENTAGE",
    category: "COMPLIANCE",
    target: 95,
    warningThreshold: 85,
    criticalThreshold: 70,
    thresholdType: "MIN",
    frequency: "DAILY",
    unit: "%",
    decimalPlaces: 1,
    applicableRoles: ["SUPER_ADMIN", "ADMIN", "GERENTE"],
    benchmark: {
      industry: 80,
      excellent: 98,
      good: 95,
      needsImprovement: 70,
    },
  },
  {
    id: "comp-ai-verification-accuracy",
    name: "Precisión de Verificación IA",
    description: "Porcentaje de aprobaciones de IA que coinciden con revisión humana. Mide la confiabilidad del sistema de IA.",
    formula: "(correct_ai_verifications / total_ai_verifications) * 100",
    metricType: "PERCENTAGE",
    category: "COMPLIANCE",
    target: 95,
    warningThreshold: 90,
    criticalThreshold: 85,
    thresholdType: "MIN",
    frequency: "WEEKLY",
    unit: "%",
    decimalPlaces: 1,
    applicableRoles: ["SUPER_ADMIN", "ADMIN", "GERENTE"],
    benchmark: {
      industry: 92,
      excellent: 97,
      good: 95,
      needsImprovement: 88,
    },
  },

  // Overall Compliance Score
  {
    id: "comp-overall-compliance",
    name: "Índice General de Cumplimiento",
    description: "Puntuación ponderada de cumplimiento que combina NOM-251, NOM-035, LFT y otros requerimientos regulatorios.",
    formula: "(nom251_score * 0.4) + (nom035_score * 0.2) + (labor_score * 0.3) + (ai_score * 0.1)",
    metricType: "PERCENTAGE",
    category: "COMPLIANCE",
    target: 95,
    warningThreshold: 85,
    criticalThreshold: 75,
    thresholdType: "MIN",
    frequency: "WEEKLY",
    unit: "%",
    decimalPlaces: 1,
    applicableRoles: ["SUPER_ADMIN", "ADMIN", "GERENTE"],
    benchmark: {
      industry: 88,
      excellent: 97,
      good: 95,
      needsImprovement: 80,
    },
  },
];

// ============================================================================
// LABOR KPIs - Employee and workforce metrics
// ============================================================================

export const laborKPIs: KpiTemplate[] = [
  // Attendance
  {
    id: "labor-attendance-rate",
    name: "Tasa de Asistencia",
    description: "Porcentaje de asistencia efectiva vs turnos programados. Incluye puntualidad y días trabajados completos.",
    formula: "(attended_shifts / scheduled_shifts) * 100",
    metricType: "PERCENTAGE",
    category: "LABOR",
    target: 95,
    warningThreshold: 90,
    criticalThreshold: 85,
    thresholdType: "MIN",
    frequency: "DAILY",
    unit: "%",
    decimalPlaces: 1,
    applicableRoles: ["SUPER_ADMIN", "ADMIN", "GERENTE", "SUPERVISOR"],
    benchmark: {
      industry: 92,
      excellent: 97,
      good: 95,
      needsImprovement: 88,
    },
  },
  {
    id: "labor-punctuality-rate",
    name: "Tasa de Puntualidad",
    description: "Porcentaje de empleados que llegan a tiempo a su turno. Considera tolerancia de 5 minutos configurada.",
    formula: "(on_time_arrivals / total_arrivals) * 100",
    metricType: "PERCENTAGE",
    category: "LABOR",
    target: 92,
    warningThreshold: 85,
    criticalThreshold: 75,
    thresholdType: "MIN",
    frequency: "DAILY",
    unit: "%",
    decimalPlaces: 1,
    applicableRoles: ["SUPER_ADMIN", "ADMIN", "GERENTE", "SUPERVISOR"],
    benchmark: {
      industry: 88,
      excellent: 95,
      good: 92,
      needsImprovement: 80,
    },
  },

  // Hours and Overtime
  {
    id: "labor-avg-hours-per-employee",
    name: "Promedio de Horas Semanales por Empleado",
    description: "Promedio de horas trabajadas semanalmente por empleado. Ideal para planificación de personal.",
    formula: "AVG(weekly_hours)",
    metricType: "TIME",
    category: "LABOR",
    target: 40,
    warningThreshold: 48,
    criticalThreshold: 54,
    thresholdType: "RANGE",
    frequency: "WEEKLY",
    unit: "hrs",
    decimalPlaces: 1,
    applicableRoles: ["SUPER_ADMIN", "ADMIN", "GERENTE"],
    benchmark: {
      industry: 42,
      excellent: 40,
      good: 42,
      needsImprovement: 50,
    },
  },
  {
    id: "labor-overtime-hours",
    name: "Horas Extra Mensuales",
    description: "Total de horas extra acumuladas en el mes. Afecta directamente los costos laborales.",
    formula: "SUM(overtime_hours)",
    metricType: "SUM",
    category: "LABOR",
    target: 50,
    warningThreshold: 150,
    criticalThreshold: 300,
    thresholdType: "MAX",
    frequency: "MONTHLY",
    unit: "hrs",
    decimalPlaces: 0,
    applicableRoles: ["SUPER_ADMIN", "ADMIN", "GERENTE"],
    benchmark: {
      industry: 100,
      excellent: 30,
      good: 80,
      needsImprovement: 200,
    },
  },
  {
    id: "labor-overtime-percentage",
    name: "Porcentaje de Horas Extra",
    description: "Proporción de horas extra vs horas regulares. Indicador de posible falta de personal.",
    formula: "(overtime_hours / regular_hours) * 100",
    metricType: "PERCENTAGE",
    category: "LABOR",
    target: 5,
    warningThreshold: 15,
    criticalThreshold: 25,
    thresholdType: "MAX",
    frequency: "MONTHLY",
    unit: "%",
    decimalPlaces: 1,
    applicableRoles: ["SUPER_ADMIN", "ADMIN", "GERENTE"],
    benchmark: {
      industry: 10,
      excellent: 3,
      good: 8,
      needsImprovement: 20,
    },
  },
  {
    id: "labor-overtime-compliance-rate",
    name: "Tasa de Cumplimiento Límite de Horas Extra",
    description: "Porcentaje de empleados que no excedieron el límite legal de horas extra (3hrs/día, 3 veces/semana).",
    formula: "(compliant_overtime_employees / total_employees) * 100",
    metricType: "PERCENTAGE",
    category: "LABOR",
    target: 100,
    warningThreshold: 95,
    criticalThreshold: 90,
    thresholdType: "MIN",
    frequency: "WEEKLY",
    unit: "%",
    decimalPlaces: 1,
    applicableRoles: ["SUPER_ADMIN", "ADMIN", "GERENTE"],
    benchmark: {
      industry: 95,
      excellent: 100,
      good: 98,
      needsImprovement: 90,
    },
  },

  // Productivity
  {
    id: "labor-tasks-per-employee",
    name: "Tareas Completadas por Empleado",
    description: "Promedio diario de tareas completadas por empleado. Mide productividad individual.",
    formula: "AVG(tasks_completed_per_employee)",
    metricType: "AVERAGE",
    category: "LABOR",
    target: 15,
    warningThreshold: 10,
    criticalThreshold: 8,
    thresholdType: "MIN",
    frequency: "DAILY",
    unit: "tareas",
    decimalPlaces: 1,
    applicableRoles: ["SUPER_ADMIN", "ADMIN", "GERENTE", "SUPERVISOR"],
    benchmark: {
      industry: 12,
      excellent: 18,
      good: 15,
      needsImprovement: 10,
    },
  },
  {
    id: "labor-time-per-task",
    name: "Tiempo Promedio por Tarea",
    description: "Tiempo promedio que toma un empleado completar una tarea. Ayuda a identificar capacitaciones necesarias.",
    formula: "AVG(task_duration_minutes)",
    metricType: "TIME",
    category: "LABOR",
    target: 20,
    warningThreshold: 35,
    criticalThreshold: 50,
    thresholdType: "MAX",
    frequency: "DAILY",
    unit: "min",
    decimalPlaces: 1,
    applicableRoles: ["SUPER_ADMIN", "ADMIN", "GERENTE"],
    benchmark: {
      industry: 25,
      excellent: 15,
      good: 20,
      needsImprovement: 40,
    },
  },

  // Employee Distribution
  {
    id: "labor-staffing-level",
    name: "Nivel de Dotación vs Requerido",
    description: "Ratio de empleados activos vs personal requerido según volumen de operación. Ideal: 95-105%.",
    formula: "(active_employees / required_employees) * 100",
    metricType: "PERCENTAGE",
    category: "LABOR",
    target: 100,
    warningThreshold: 90,
    criticalThreshold: 85,
    thresholdType: "RANGE",
    frequency: "WEEKLY",
    unit: "%",
    decimalPlaces: 1,
    applicableRoles: ["SUPER_ADMIN", "ADMIN", "GERENTE"],
    benchmark: {
      industry: 95,
      excellent: 100,
      good: 98,
      needsImprovement: 85,
    },
  },
  {
    id: "labor-turnover-rate",
    name: "Tasa de Rotación de Personal",
    description: "Porcentaje de rotación de empleados mensual. Indicador de satisfacción y retención.",
    formula: "(employees_left / avg_employees) * 100",
    metricType: "PERCENTAGE",
    category: "LABOR",
    target: 5,
    warningThreshold: 10,
    criticalThreshold: 15,
    thresholdType: "MAX",
    frequency: "MONTHLY",
    unit: "%",
    decimalPlaces: 1,
    applicableRoles: ["SUPER_ADMIN", "ADMIN", "GERENTE"],
    benchmark: {
      industry: 12,
      excellent: 4,
      good: 8,
      needsImprovement: 18,
    },
  },

  // Break Compliance
  {
    id: "labor-break-taken-rate",
    name: "Tasa de Toma de Pausas",
    description: "Porcentaje de empleados que tomaron sus pausas activas programadas. Obligatorio por ley.",
    formula: "(breaks_taken / breaks_required) * 100",
    metricType: "PERCENTAGE",
    category: "LABOR",
    target: 98,
    warningThreshold: 90,
    criticalThreshold: 80,
    thresholdType: "MIN",
    frequency: "DAILY",
    unit: "%",
    decimalPlaces: 1,
    applicableRoles: ["SUPER_ADMIN", "ADMIN", "GERENTE", "SUPERVISOR"],
    benchmark: {
      industry: 85,
      excellent: 98,
      good: 95,
      needsImprovement: 75,
    },
  },
  {
    id: "labor-break-duration-compliance",
    name: "Cumplimiento Duración de Pausas",
    description: "Porcentaje de pausas con duración correcta (30min para 8hrs, 15min para 4-6hrs).",
    formula: "(compliant_break_duration / breaks_taken) * 100",
    metricType: "PERCENTAGE",
    category: "LABOR",
    target: 100,
    warningThreshold: 90,
    criticalThreshold: 80,
    thresholdType: "MIN",
    frequency: "DAILY",
    unit: "%",
    decimalPlaces: 1,
    applicableRoles: ["SUPER_ADMIN", "ADMIN", "GERENTE"],
    benchmark: {
      industry: 88,
      excellent: 98,
      good: 95,
      needsImprovement: 80,
    },
  },

  // Shift Coverage
  {
    id: "labor-shift-coverage",
    name: "Cobertura de Turnos",
    description: "Porcentaje de turnos cubiertos vs programados. Mide disponibilidad de personal.",
    formula: "(covered_shifts / scheduled_shifts) * 100",
    metricType: "PERCENTAGE",
    category: "LABOR",
    target: 95,
    warningThreshold: 90,
    criticalThreshold: 85,
    thresholdType: "MIN",
    frequency: "DAILY",
    unit: "%",
    decimalPlaces: 1,
    applicableRoles: ["SUPER_ADMIN", "ADMIN", "GERENTE", "SUPERVISOR"],
    benchmark: {
      industry: 92,
      excellent: 97,
      good: 95,
      needsImprovement: 88,
    },
  },
];

// ============================================================================
// INVENTORY KPIs - Stock and supply chain metrics
// ============================================================================

export const inventoryKPIs: KpiTemplate[] = [
  // Stock Levels
  {
    id: "inv-stock-accuracy",
    name: "Precisión de Inventario",
    description: "Porcentaje de coincidencia entre inventario físico y sistema. Realizado mediante conteos cíclicos.",
    formula: "(accurate_items / total_items) * 100",
    metricType: "PERCENTAGE",
    category: "INVENTORY",
    target: 98,
    warningThreshold: 95,
    criticalThreshold: 90,
    thresholdType: "MIN",
    frequency: "WEEKLY",
    unit: "%",
    decimalPlaces: 1,
    applicableRoles: ["SUPER_ADMIN", "ADMIN", "GERENTE", "SUPERVISOR"],
    benchmark: {
      industry: 95,
      excellent: 99,
      good: 98,
      needsImprovement: 92,
    },
  },
  {
    id: "inv-stockout-rate",
    name: "Tasa de Desabasto (Stockouts)",
    description: "Porcentaje de productos sin stock disponible. Crítico para operación del restaurante.",
    formula: "(out_of_stock_items / total_sku_count) * 100",
    metricType: "PERCENTAGE",
    category: "INVENTORY",
    target: 2,
    warningThreshold: 5,
    criticalThreshold: 10,
    thresholdType: "MAX",
    frequency: "DAILY",
    unit: "%",
    decimalPlaces: 1,
    applicableRoles: ["SUPER_ADMIN", "ADMIN", "GERENTE", "SUPERVISOR"],
    benchmark: {
      industry: 5,
      excellent: 1,
      good: 3,
      needsImprovement: 10,
    },
  },
  {
    id: "inv-critical-stockout-count",
    name: "Desabastos Críticos",
    description: "Número de productos críticos (insumos esenciales) sin stock. Puede detener operaciones.",
    formula: "critical_out_of_stock_items",
    metricType: "COUNT",
    category: "INVENTORY",
    target: 0,
    warningThreshold: 2,
    criticalThreshold: 5,
    thresholdType: "MAX",
    frequency: "REALTIME",
    unit: "productos",
    decimalPlaces: 0,
    applicableRoles: ["SUPER_ADMIN", "ADMIN", "GERENTE", "SUPERVISOR"],
    benchmark: {
      industry: 1,
      excellent: 0,
      good: 0,
      needsImprovement: 5,
    },
  },

  // Expiration Management
  {
    id: "inv-expiration-alerts",
    name: "Alertas de Productos por Vencer",
    description: "Cantidad de productos que vencerán en los próximos 7 días. Permite planificar promociones o ajustes.",
    formula: "expiring_items_7days",
    metricType: "COUNT",
    category: "INVENTORY",
    target: 10,
    warningThreshold: 25,
    criticalThreshold: 50,
    thresholdType: "MAX",
    frequency: "DAILY",
    unit: "productos",
    decimalPlaces: 0,
    applicableRoles: ["SUPER_ADMIN", "ADMIN", "GERENTE", "SUPERVISOR"],
    benchmark: {
      industry: 20,
      excellent: 5,
      good: 15,
      needsImprovement: 40,
    },
  },
  {
    id: "inv-expired-items",
    name: "Productos Vencidos",
    description: "Cantidad de productos que vencieron y deben descartarse. Pérdida directa.",
    formula: "expired_items",
    metricType: "COUNT",
    category: "INVENTORY",
    target: 0,
    warningThreshold: 5,
    criticalThreshold: 15,
    thresholdType: "MAX",
    frequency: "DAILY",
    unit: "productos",
    decimalPlaces: 0,
    applicableRoles: ["SUPER_ADMIN", "ADMIN", "GERENTE", "SUPERVISOR"],
    benchmark: {
      industry: 5,
      excellent: 0,
      good: 2,
      needsImprovement: 15,
    },
  },
  {
    id: "inv-expiration-rate",
    name: "Tasa de Vencimiento",
    description: "Porcentaje del inventario total que se venció. Indicador de gestión de inventario.",
    formula: "(expired_items / total_items) * 100",
    metricType: "PERCENTAGE",
    category: "INVENTORY",
    target: 1,
    warningThreshold: 3,
    criticalThreshold: 5,
    thresholdType: "MAX",
    frequency: "WEEKLY",
    unit: "%",
    decimalPlaces: 1,
    applicableRoles: ["SUPER_ADMIN", "ADMIN", "GERENTE"],
    benchmark: {
      industry: 3,
      excellent: 0.5,
      good: 2,
      needsImprovement: 6,
    },
  },

  // Waste and Loss
  {
    id: "inv-waste-percentage",
    name: "Porcentaje de Merma",
    description: "Valor de productos vencidos/dañados vs valor total del inventario. Mide eficiencia en gestión.",
    formula: "(waste_value / inventory_value) * 100",
    metricType: "PERCENTAGE",
    category: "INVENTORY",
    target: 2,
    warningThreshold: 5,
    criticalThreshold: 8,
    thresholdType: "MAX",
    frequency: "WEEKLY",
    unit: "%",
    decimalPlaces: 1,
    applicableRoles: ["SUPER_ADMIN", "ADMIN", "GERENTE"],
    benchmark: {
      industry: 4,
      excellent: 1,
      good: 3,
      needsImprovement: 8,
    },
  },
  {
    id: "inv-damaged-items",
    name: "Productos Dañados",
    description: "Cantidad de productos reportados como dañados en la semana.",
    formula: "damaged_items",
    metricType: "COUNT",
    category: "INVENTORY",
    target: 5,
    warningThreshold: 15,
    criticalThreshold: 30,
    thresholdType: "MAX",
    frequency: "WEEKLY",
    unit: "productos",
    decimalPlaces: 0,
    applicableRoles: ["SUPER_ADMIN", "ADMIN", "GERENTE", "SUPERVISOR"],
    benchmark: {
      industry: 10,
      excellent: 3,
      good: 8,
      needsImprovement: 25,
    },
  },

  // Receiving
  {
    id: "inv-receiving-accuracy",
    name: "Precisión en Recepción",
    description: "Porcentaje de recepciones que coinciden con la orden de compra (cantidad y calidad).",
    formula: "(accurate_receipts / total_receipts) * 100",
    metricType: "PERCENTAGE",
    category: "INVENTORY",
    target: 98,
    warningThreshold: 95,
    criticalThreshold: 90,
    thresholdType: "MIN",
    frequency: "DAILY",
    unit: "%",
    decimalPlaces: 1,
    applicableRoles: ["SUPER_ADMIN", "ADMIN", "GERENTE", "SUPERVISOR"],
    benchmark: {
      industry: 95,
      excellent: 99,
      good: 98,
      needsImprovement: 92,
    },
  },
  {
    id: "inv-receiving-temperature-compliance",
    name: "Cumplimiento Temperatura en Recepción",
    description: "Porcentaje de productos recibidos dentro de rango de temperatura seguro.",
    formula: "(temp_compliant_receipts / total_receipts) * 100",
    metricType: "PERCENTAGE",
    category: "INVENTORY",
    target: 100,
    warningThreshold: 98,
    criticalThreshold: 95,
    thresholdType: "MIN",
    frequency: "DAILY",
    unit: "%",
    decimalPlaces: 1,
    applicableRoles: ["SUPER_ADMIN", "ADMIN", "GERENTE", "SUPERVISOR"],
    benchmark: {
      industry: 98,
      excellent: 100,
      good: 99,
      needsImprovement: 95,
    },
  },

  // Inventory Turns
  {
    id: "inv-turnover-rate",
    name: "Rotación de Inventario",
    description: "Número de veces que el inventario se renueva mensualmente. Mayor es mejor (menos capital inmovilizado).",
    formula: "cost_of_goods_sold / avg_inventory_value",
    metricType: "RATIO",
    category: "INVENTORY",
    target: 4,
    warningThreshold: 2.5,
    criticalThreshold: 1.5,
    thresholdType: "MIN",
    frequency: "MONTHLY",
    unit: "turns",
    decimalPlaces: 1,
    applicableRoles: ["SUPER_ADMIN", "ADMIN", "GERENTE"],
    benchmark: {
      industry: 3,
      excellent: 6,
      good: 4,
      needsImprovement: 2,
    },
  },
  {
    id: "inv-days-on-hand",
    name: "Días de Inventario Disponible",
    description: "Días promedio de inventario disponible. Balance entre disponibilidad y capital inmovilizado.",
    formula: "(avg_inventory_value / daily_cost_of_goods_sold)",
    metricType: "TIME",
    category: "INVENTORY",
    target: 7,
    warningThreshold: 14,
    criticalThreshold: 21,
    thresholdType: "RANGE",
    frequency: "WEEKLY",
    unit: "días",
    decimalPlaces: 0,
    applicableRoles: ["SUPER_ADMIN", "ADMIN", "GERENTE"],
    benchmark: {
      industry: 10,
      excellent: 5,
      good: 7,
      needsImprovement: 18,
    },
  },

  // Stock Alerts
  {
    id: "inv-low-stock-alerts",
    name: "Alertas de Stock Bajo",
    description: "Número de productos por debajo del punto de reorden. Requiere atención inmediata.",
    formula: "low_stock_items",
    metricType: "COUNT",
    category: "INVENTORY",
    target: 10,
    warningThreshold: 30,
    criticalThreshold: 60,
    thresholdType: "MAX",
    frequency: "DAILY",
    unit: "productos",
    decimalPlaces: 0,
    applicableRoles: ["SUPER_ADMIN", "ADMIN", "GERENTE", "SUPERVISOR"],
    benchmark: {
      industry: 25,
      excellent: 5,
      good: 15,
      needsImprovement: 50,
    },
  },
  {
    id: "inv-minimum-stock-compliance",
    name: "Cumplimiento Stock Mínimo",
    description: "Porcentaje de productos por encima del stock mínimo configurado.",
    formula: "(items_above_minimum / total_items) * 100",
    metricType: "PERCENTAGE",
    category: "INVENTORY",
    target: 95,
    warningThreshold: 90,
    criticalThreshold: 85,
    thresholdType: "MIN",
    frequency: "DAILY",
    unit: "%",
    decimalPlaces: 1,
    applicableRoles: ["SUPER_ADMIN", "ADMIN", "GERENTE"],
    benchmark: {
      industry: 90,
      excellent: 97,
      good: 95,
      needsImprovement: 85,
    },
  },
];

// ============================================================================
// CORPORATE KPIs - Multi-branch comparison and consolidated metrics
// ============================================================================

export const corporateKPIs: KpiTemplate[] = [
  // Branch Comparison
  {
    id: "corp-branch-performance-ranking",
    name: "Ranking de Rendimiento por Sucursal",
    description: "Clasificación de sucursales por índice de rendimiento compuesto (1-15). Permite identificar mejores prácticas.",
    formula: "RANK(branch_performance_score)",
    metricType: "COUNT",
    category: "OPERATIONS",
    target: 1,
    warningThreshold: 8,
    criticalThreshold: 12,
    thresholdType: "MIN",
    frequency: "WEEKLY",
    unit: "posición",
    decimalPlaces: 0,
    applicableRoles: ["SUPER_ADMIN", "ADMIN"],
    benchmark: {
      industry: 7,
      excellent: 1,
      good: 5,
      needsImprovement: 12,
    },
  },
  {
    id: "corp-inter-branch-variance",
    name: "Variación Entre Sucursales",
    description: "Desviación estándar del rendimiento entre sucursales. Menor variación indica estándares uniformes.",
    formula: "STDEV(branch_performance_scores)",
    metricType: "PERCENTAGE",
    category: "OPERATIONS",
    target: 10,
    warningThreshold: 20,
    criticalThreshold: 30,
    thresholdType: "MAX",
    frequency: "WEEKLY",
    unit: "%",
    decimalPlaces: 1,
    applicableRoles: ["SUPER_ADMIN", "ADMIN"],
    benchmark: {
      industry: 18,
      excellent: 8,
      good: 12,
      needsImprovement: 28,
    },
  },

  // Consolidated Metrics
  {
    id: "corp-total-active-branches",
    name: "Sucursales Activas",
    description: "Número de sucursales operando activamente en el sistema.",
    formula: "COUNT(active_branches)",
    metricType: "COUNT",
    category: "OPERATIONS",
    target: 15,
    warningThreshold: 3,
    criticalThreshold: 2,
    thresholdType: "MIN",
    frequency: "DAILY",
    unit: "sucursales",
    decimalPlaces: 0,
    applicableRoles: ["SUPER_ADMIN", "ADMIN"],
    benchmark: {
      industry: 8,
      excellent: 15,
      good: 12,
      needsImprovement: 5,
    },
  },
  {
    id: "corp-branch-compliance-consistency",
    name: "Consistencia de Cumplimiento",
    description: "Porcentaje de sucursales que mantienen cumplimiento >90%. Mide estándar corporativo.",
    formula: "(branches_above_90_compliance / total_branches) * 100",
    metricType: "PERCENTAGE",
    category: "COMPLIANCE",
    target: 100,
    warningThreshold: 85,
    criticalThreshold: 70,
    thresholdType: "MIN",
    frequency: "WEEKLY",
    unit: "%",
    decimalPlaces: 1,
    applicableRoles: ["SUPER_ADMIN", "ADMIN"],
    benchmark: {
      industry: 85,
      excellent: 100,
      good: 95,
      needsImprovement: 70,
    },
  },
];

// ============================================================================
// ALL KPIs COMBINED
// ============================================================================

export const allRestaurantKPIs: KpiTemplate[] = [
  ...operationsKPIs,
  ...complianceKPIs,
  ...laborKPIs,
  ...inventoryKPIs,
  ...corporateKPIs,
];

// Helper functions
export const getKPIsByCategory = (category: KpiTemplate["category"]) => {
  return allRestaurantKPIs.filter((kpi) => kpi.category === category);
};

export const getKPIsByRole = (role: string) => {
  return allRestaurantKPIs.filter((kpi) => kpi.applicableRoles.includes(role));
};

export const getKPITemplateById = (id: string) => {
  return allRestaurantKPIs.find((kpi) => kpi.id === id);
};

export const getKPIsByFrequency = (frequency: KpiTemplate["frequency"]) => {
  return allRestaurantKPIs.filter((kpi) => kpi.frequency === frequency);
};

export const getCriticalKPIs = () => {
  return allRestaurantKPIs.filter((kpi) => 
    kpi.thresholdType === "MIN" && kpi.target >= 90 ||
    kpi.id.includes("critical") ||
    kpi.id.includes("temperature") ||
    kpi.id.includes("nom251")
  );
};
